# Generated by Django 4.0.4 on 2022-05-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default=0, max_length=1)),
                ('new_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.city')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.vehicle')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'Event',
                'ordering': ['date_create'],
            },
        ),
    ]
