# Generated by Django 4.0.4 on 2022-05-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_created'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
